name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel_build:
    name: Laravel Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Setup Environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Create SQLite Database
        run: touch database/database.sqlite

      - name: Run Database Migrations and Seeders
        run: php artisan migrate:fresh --seed

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node.js Dependencies
        run: npm install

      - name: Build Node.js Assets
        run: npm run build

  laravel_test:
    name: Laravel Test
    runs-on: ubuntu-latest
    needs: laravel_build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Setup Environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Create SQLite Database
        run: touch database/database.sqlite

      - name: Run Database Migrations and Seeders
        run: php artisan migrate:fresh --seed

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node.js Dependencies
        run: npm install

      - name: Run Tests
        run: php artisan test

  notify:
    name: Telegram Notification
    runs-on: ubuntu-latest
    needs: 
      - laravel_build
      - laravel_test

    steps:
      - name: Send Telegram Notification on Success
        if: ${{ needs.laravel_build.result == 'success' && needs.laravel_test.result == 'success' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Proses build dan test Laravel berhasil!"

      - name: Send Telegram Notification on Failure
        if: ${{ needs.laravel_build.result == 'failure' || needs.laravel_test.result == 'failure' }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$ {{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="Proses build atau test Laravel gagal!"
